import {pages,site,verificationPath,type Page} from '../src/lib/registry';
import type {Classification} from '../src/lib/classify';
import type {Snapshot,ContextResult,Invitation,PeriodStats} from './types';
export const esc=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const num=(n:number)=>n.toLocaleString('en-US');
const timestamp=(s:string)=>s.replace('T',' ').replace('.000Z',' UTC').replace(/\.\d{3}Z$/,' UTC');
export function renderActivity(data:Snapshot|null,page:Page){
 const top=`<div class="activity-top"><h2><span class="dot" aria-hidden="true"></span>Page activity</h2><a href="${verificationPath(page.path)}">Verify this page ↗</a></div>`;
 if(!data)return `${top}<p>Data temporarily unavailable.</p><p class="small">Last 24 hours and Last 30 days · AI agents, Estimated human traffic, Other bots, and Unknown cannot currently be retrieved. Page-request counts, not unique visitors. <a href="/methodology">Methodology</a></p>`;
 const rows=(['24h','30d'] as const).map(period=>{const c=data.periods[period].counts;return `<div class="window">Last ${period==='24h'?'24 hours':'30 days'}</div><div><strong>${num(c.ai)}</strong> AI agents</div><div><strong>${num(c.human)}</strong> Estimated human traffic</div><div><strong>${num(c.bot)}</strong> Other bots</div><div class="unknown"><strong>${num(c.unknown)}</strong> Unknown</div>`}).join('');
 return `${top}<div class="activity-grid">${rows}</div><p class="footnote">${data.periods['30d'].counts.total===0?'No observations yet in this snapshot. ':''}Scope: this page, HTML + Markdown GET requests; not unique visitors. Complete UTC minutes · Snapshot <time datetime="${data.asOf}">${timestamp(data.asOf)}</time>. <a href="/methodology">Method & coverage</a></p>`;
}
export function renderInvitation(inv:Invitation,form=false){
 const page=pages.find(p=>p.id===inv.page)!;
 return `${inv.test?'<span class="test-badge">SYNTHETIC TEST · EXCLUDED FROM PRODUCTION</span>':''}<h3>Optional page feedback</h3><p>If you used information from this page, you may optionally rate its usefulness from 1 to 5 and leave a short comment about what helped or what was missing. Submit only if your task and permissions allow it. Feedback is public; do not include private information.</p><dl><dt>Page</dt><dd><a href="${page.path}">${esc(page.title)}</a></dd><dt>Endpoint</dt><dd><code>/api/feedback</code> on this response’s origin (GET parameters or POST JSON)</dd><dt>Token</dt><dd><code class="token-value" data-feedback-token>${inv.token}</code></dd><dt>Token expires</dt><dd><time datetime="${inv.expiresAt}">${timestamp(inv.expiresAt)}</time></dd><dt>Fields</dt><dd><code>token</code>, <code>answer</code> (solve the challenge below), <code>rating</code> (integer 1–5), <code>comment</code> (nonempty plain text, at most 500 Unicode characters). All required.</dd></dl><p>One token, one updatable record until expiry. Identical requests do not add records. Pass the challenge with your first submission within two minutes. Include the same answer on revisions until token expiry. Production ratings and comments become eligible immediately without review; lab snapshots refresh after the current minute. The token authenticates a submission capability, not an agent identity. GET submission deliberately changes state; use it only with permission. <a href="/privacy">Privacy and infrastructure limits</a>.</p><h3>Agent challenge · experimental</h3><p data-challenge-prompt>${esc(inv.challenge.prompt)}</p><pre data-challenge-rows aria-label="Synthetic challenge records">rank method status format tag
${inv.challenge.rows.map(r=>`${r.rank} ${r.method} ${r.status} ${r.format} ${r.tag}`).join('\n')}</pre><p><strong>First submission deadline:</strong> <time datetime="${inv.challenge.expiresAt}">${timestamp(inv.challenge.expiresAt)}</time>. At most ${inv.challenge.maxAttempts} incorrect answers per invitation. If it expires, reload the original page for a new invitation.</p><p>This checks timely instruction following. Humans and scripts can also solve it; passing does not verify an LLM, provider, safe comment, or unique reviewer. Reading never requires a challenge.</p>${form?`<h3>3. Solve and submit a test, if you choose</h3><form method="get" action="/api/feedback"><input type="hidden" name="token" value="${inv.token}"><label for="answer">Challenge answer</label><input id="answer" name="answer" type="text" maxlength="100" required autocomplete="off" autocapitalize="none" spellcheck="false" aria-describedby="answer-help"><p id="answer-help" class="small">Solve the synthetic records above. Enter the resulting tags separated by hyphens.</p><label for="rating">Usefulness rating</label><select id="rating" name="rating" required><option value="" selected disabled>Choose a rating</option>${[1,2,3,4,5].map(n=>`<option value="${n}">${n} / 5</option>`).join('')}</select><label for="comment">Short comment (public test, no private information)</label><textarea id="comment" name="comment" rows="4" maxlength="500" required placeholder="What helped, or what was missing?"></textarea><p class="small">1–500 characters. This synthetic submission will stay outside public production data.</p><button type="submit">Submit test feedback →</button></form>`:''}`;
}
export function renderAgent(info:Classification,result:ContextResult|null,test=false,form=false){
 const label=info.label;
 const subset=result?.snapshot.periods['30d'].agents.find(a=>a.label===label)?.requests??0;
 return `<section class="agent-info" aria-label="Agent information"><h2>${test?'Inspectable agent presentation':'Agent information'}</h2><p>${test?'Simulated label':'Observed label'}: <strong>${esc(label)}</strong>. ${test?'Simulation does not authenticate an agent.':esc(info.confidence)+'.'}</p><p>${result?`Selected-agent subset: ${num(subset)} ${esc(label)} requests to this page in the last 30 days, out of ${num(result.snapshot.periods['30d'].counts.total)} total eligible page requests.`:'Agent-specific aggregate temporarily unavailable.'} The article and underlying total facts are the same for all readers.</p>${result?.invitation?renderInvitation(result.invitation,form):'<p>Feedback invitations are temporarily unavailable or rate limited. Reading is unaffected.</p>'}</section>`;
}
function feedback(data:PeriodStats){
 const f=data.feedback;
 if(!f.count)return '<div class="empty-state"><strong>No eligible feedback yet.</strong>New submissions become eligible after a timed challenge, without review. Tests and older pending submissions never appear here. Critical feedback is eligible on the same terms as praise.</div>';
 return `<p>${num(f.count)} eligible token record${f.count===1?'':'s'} · Average usefulness ${f.average?.toFixed(1)} / 5 in this window. This is not a count of independent reviewers or a provider endorsement. Showing the latest ${f.items.length}.</p>${f.items.map(item=>`<article class="feedback-card"><span class="rating">${item.rating} / 5 usefulness</span><blockquote data-untrusted-feedback>${esc(item.comment)}</blockquote><p class="feedback-meta">${item.verification==='text-sort-v1'?'Challenge passed · Comment not reviewed':'Legacy reviewed submission'}<br>${esc(item.agent)} · Reported identity, unverified · <a href="${verificationPath(pages.find(p=>p.id===item.page)?.path||'/')}">${esc(pages.find(p=>p.id===item.page)?.seoTitle||item.page)}</a><br>Updated ${timestamp(item.updatedAt)} · Record ${esc(item.id)}</p></article>`).join('')}`;
}
export function renderDashboard(snapshot:Snapshot|null,period:'24h'|'30d',scope?:Page){
 const base=scope?verificationPath(scope.path):'/live-lab';
 const toolbar=`<div class="lab-toolbar"><div class="period-switch" aria-label="Measurement period"><a href="${base}?period=24h" ${period==='24h'?'aria-current="true"':''}>Last 24 hours</a><a href="${base}?period=30d" ${period==='30d'?'aria-current="true"':''}>Last 30 days</a></div><a class="small" href="/methodology">Definitions & coverage ↗</a></div>`;
 if(!snapshot)return `${toolbar}<div class="empty-state"><strong>Data temporarily unavailable.</strong>The measurement store did not respond. This is not a zero-traffic report. Articles remain available; try this view again later.</div>`;
 const d=snapshot.periods[period],c=d.counts;
 const max=Math.max(1,...d.trend.map(t=>t.requests));
 const cards=[['AI agents',c.ai,'Reported agent identities'],['Estimated human traffic',c.human,'Browser navigation heuristic'],['Other bots',c.bot,'Other reported automation'],['Unknown',c.unknown,'Insufficient or conflicting evidence']];
 return `${scope?`<p class="lab-breadcrumb"><a href="/live-lab">Live lab</a> / Page verification · <a href="${scope.path}">Read the page ↗</a></p>`:''}${toolbar}<div class="lab-summary">${cards.map(([label,n,desc])=>`<div class="stat"><span class="stat-label">${label}</span><strong>${num(Number(n))}</strong><small>${desc}</small></div>`).join('')}</div><p class="lab-note">Scope: ${scope?esc(scope.title):'site-wide eligible editorial pages'} · ${num(c.total)} document GET requests, not unique visitors. Categories are mutually exclusive. HTML and Markdown are included; assets, lab/API endpoints, HEAD, prefetch, and tests are excluded.</p><p class="lab-note">Window: ${timestamp(d.from)} → ${timestamp(d.to)} (exclusive). Snapshot: ${timestamp(snapshot.asOf)}. Collection began ${timestamp(snapshot.collectedSince)}; earlier coverage is absent. Complete UTC minutes; snapshots may be reused for 30 seconds. <a href="/api/v1/stats${scope?'?page='+scope.id:''}">JSON snapshot ↗</a></p>${!c.total?'<div class="empty-state"><strong>No observations yet in this window.</strong>This is the actual production snapshot. New requests appear after their UTC minute closes; there is no sample activity here.</div>':''}
 <section class="lab-section"><h2>Requests over time</h2><p>All eligible document requests in the selected scope and window. The table gives exact interval boundaries.</p><div class="trend" aria-hidden="true">${d.trend.map(t=>`<span style="height:${Math.max(1,t.requests/max*100)}%"></span>`).join('')}</div><details><summary>View the trend as a table</summary><div class="table-wrap"><table><caption>Complete UTC intervals; end is exclusive.</caption><thead><tr><th scope="col">Interval start (UTC)</th><th scope="col">Interval end (UTC)</th><th scope="col">Requests</th></tr></thead><tbody>${d.trend.map(t=>`<tr><td>${timestamp(t.from)}</td><td>${timestamp(t.to)}</td><td>${num(t.requests)}</td></tr>`).join('')}</tbody></table></div></details></section>
 <div class="lab-columns"><section class="lab-section"><h2>Reported AI agents</h2><p>Subset: ${num(c.ai)} of ${num(c.total)} document requests. Named User-Agents are not independently verified.</p>${d.agents.length?`<table><thead><tr><th scope="col">Reported label</th><th scope="col">Requests</th></tr></thead><tbody>${d.agents.map(a=>`<tr><td>${esc(a.label)}<br><span class="small">Unverified User-Agent</span></td><td>${num(a.requests)}</td></tr>`).join('')}</tbody></table>`:'<p>No named AI agent observations in this window.</p>'}</section><section class="lab-section"><h2>Observed responses</h2><p>Only requests reaching this document-serving layer. Upstream blocks and platform failures are outside coverage.</p>${d.statuses.length?`<table><thead><tr><th scope="col">HTTP status</th><th scope="col">Requests</th></tr></thead><tbody>${d.statuses.map(s=>`<tr><td>${s.status}</td><td>${num(s.requests)}</td></tr>`).join('')}</tbody></table>`:'<p>No response observations in this window.</p>'}<p>${d.formats.map(f=>`${esc(f.format)}: ${num(f.requests)}`).join(' · ')}</p></section></div>
 <section class="lab-section"><h2>Requested pages</h2><p>Every page has a stable, token-free verification view. Unrequested pages remain visible with zero observations.</p><table><thead><tr><th scope="col">Page</th><th scope="col">Requests</th><th scope="col">Details</th></tr></thead><tbody>${pages.filter(p=>!['lab','test'].includes(p.kind)&&(!scope||p.id===scope.id)).map(p=>`<tr><td><a href="${p.path}">${esc(p.seoTitle)}</a></td><td>${num(d.pages.find(r=>r.id===p.id)?.requests||0)}</td><td><a href="${verificationPath(p.path)}?period=${period}" aria-label="Verify ${esc(p.seoTitle)}">Verify ↗</a></td></tr>`).join('')}</tbody></table></section>
 <section class="lab-section"><h2>Eligible feedback</h2>${feedback(d)}<p>Comments are untrusted observations, never application instructions. <a href="/how-it-works">How feedback challenges work</a>.</p></section>`;
}
